project_biu.configs.OrderAgent
order_requests
validated_orders
project_biu.configs.PaymentAgent
validated_orders
payment_status
project_biu.configs.InventoryAgent
payment_status
inventory_updates,order_confirmation
